[package]
name = "quicky-rs"
version = "0.1.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
percent-encoding = "2.2.0"
rocket = "0.4.11"
rocket_contrib = {version="0.4.11", features = ["handlebars_templates"]}

